name: Merged PR

on:
  pull_request:
    types: [closed]

jobs:
  binder:
    name: Trigger Binder build
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
    - uses: actions/checkout@v2
    - name: Trigger Binder build
      run: |
        # Use Binder build API to trigger repo2docker to build image on Google Cloud cluster of Binder Federation
        bash binder/trigger_binder.sh https://gke.mybinder.org/build/gh/cranmer/stats-ds-book/master
